# Generated by Django 4.0.4 on 2022-07-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_cat_moive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release', models.IntegerField()),
                ('director', models.CharField(max_length=100)),
                ('music', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Moive',
        ),
    ]
