# Generated by Django 4.0.4 on 2022-07-20 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_movie_delete_moive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Watched Date')),
                ('time', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('N', 'Night')], default='M', max_length=1, verbose_name='Meal Period')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.movie')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
